[workspace]
members = [
  "../../websites/cses/introductory_problems/weird_algorithm",
  "../../websites/cses/introductory_problems/missing_number",
  "../../websites/cses/sorting_and_searching/distinct_numbers",
  "../../websites/cses/sorting_and_searching/apartments",
]
